name: Build App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run dist

      - name: Package Electron app
        run: npx electron-builder --win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: XavrosApp
          path: dist/
